version: '2'
services:

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "sleep 10 &&
                      python manage.py migrate &&
                      python manage.py flush --noinput &&
                      python manage.py loaddata user.json &&
                      python manage.py runserver 0.0.0.0:8000"

    image: django
    container_name: server
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db